# Generated by Django 3.2.12 on 2024-02-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_insert_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insert_Students',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
